# This is a basic workflow that is manually triggered

name: Build Image

on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Build image
      run: git clone https://gitlab.com/akoziland/akoziland-linux && ./akoziland-linux/build.sh https://gitlab.com/akoziland-initramfs

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Akoziland
        path: akoziland-linux/out/boot
        retention-days: 3
